/** Private adversarial fixtures. This module must never enter the frontend bundle. */
export const hiddenInputs: Record<string, unknown[]> = {
  'find-max': [[7], [0, 0, 0], [-2, -9], [9, 9, 2], [9, 3, 1], [1, 3, 9], [-1_000_000_000, 1_000_000_000], Array.from({ length: 100_000 }, (_, i) => i - 50_000)],
  'sum-even': [[], [-2, -4, -9], [0], [10_000, -10_000, 3], Array.from({ length: 1_000 }, (_, i) => i - 500)],
  'count-vowels': ['', 'AEIOUaeiou', 'yY!', 'a'.repeat(100_000)],
  'is-palindrome': ['', '., !', '0P', 'Aa', 'race a car', 'a'.repeat(100_000)],
  fizzbuzz: [0, 1, 15, 30],
  'leap-year': [1, 4, 100, 400, 2100, 2400],
  'digit-sum': ['0', '999999999999999999999999999999999999999999', '000001', '9'.repeat(100_000)],
  'interval-overlap': [{ a: [-5, 5], b: [-2, 2] }, { a: [0, 0], b: [0, 0] }, { a: [5, 7], b: [1, 3] }, { a: [-10, -5], b: [-7, -3] }],
  'roman-numeral': ['IV', 'IX', 'XL', 'XC', 'CD', 'CM', 'MMMCMXCIX', 'LVIII'],
  'expression-eval': ['0', '1 + 2 * 3', '(1 + 2) * 3', '8 - (2 - 3)', '10 - 3 * 2 + 4', '('.repeat(500) + '7' + ')'.repeat(500)],
  'binary-search': [{ values: [1, 1, 1], target: 1 }, { values: [1, 2, 3], target: 3 }, { values: [1, 2, 3], target: -1 }, { values: [], target: 5 }],
  'two-sum': [{ values: [], target: 0 }, { values: [5], target: 10 }, { values: [0, 0], target: 0 }, { values: [1, 1, 3, 3], target: 4 }, { values: [-3, 4, 3, 90], target: 0 }],
  'merge-sorted': [{ a: [], b: [] }, { a: [1], b: [] }, { a: [-5, -1, 0], b: [-5, 3] }, { a: [1, 1], b: [1, 1] }],
  'rotate-array': [{ values: [], k: 100 }, { values: [1, 2, 3], k: 0 }, { values: [1, 2, 3], k: 1_000_000_000 }, { values: [7], k: 8 }],
  gcd: [[0, 0], [0, -18], [-48, -18], [1_000_000_000, 10], [999_999_937, 2]],
  'anagram-groups': [[], ['', '', 'a'], ['ab', 'ba', 'aa', 'aab', 'aba'], ['z', 'a', 'z']],
  'sliding-window-max': [{ values: [3, 2, 1], k: 1 }, { values: [3, 2, 1], k: 3 }, { values: [-2, -1, -1, -3], k: 2 }, { values: Array.from({ length: 10_000 }, (_, i) => 10_000 - i), k: 31 }],
  'longest-unique-substring': ['', 'abba', 'dvdf', 'a A a', 'abcdefghijklmnopqrstuvwxyz'],
  'coin-change': [{ coins: [2], amount: 0 }, { coins: [2, 5], amount: 3 }, { coins: [1, 3, 4], amount: 6 }, { coins: [7, 11], amount: 77 }],
  'interval-merge': [[], [[1, 4], [2, 3]], [[5, 5], [1, 2], [2, 5]], [[-5, -2], [-1, 0]], [[1, 1], [1, 1]]],
  'topological-sort': [{ n: 0, edges: [] }, { n: 4, edges: [] }, { n: 4, edges: [[2, 0], [2, 1], [0, 3]] }, { n: 1, edges: [[0, 0]] }, { n: 3, edges: [[0, 1], [1, 2], [2, 0]] }],
  'shortest-path': [
    { graph: [[]], start: 0, end: 0 },
    { graph: [[{ to: 1, weight: 0 }], []], start: 0, end: 1 },
    { graph: [[{ to: 1, weight: 9 }, { to: 1, weight: 2 }, { to: 2, weight: 2 }], [{ to: 3, weight: 1 }], [{ to: 3, weight: 1 }], []], start: 0, end: 3 },
    { graph: [[{ to: 1, weight: 0 }], [{ to: 0, weight: 0 }, { to: 2, weight: 1 }], []], start: 0, end: 2 },
    { graph: [[], []], start: 1, end: 0 },
    { graph: Array.from({ length: 1_000 }, (_, i) => i < 999 ? [{ to: i + 1, weight: 1 }] : []), start: 0, end: 999 },
  ],
  'edit-distance': [{ a: '', b: '' }, { a: 'a', b: '' }, { a: 'abc', b: 'abc' }, { a: 'abc', b: 'acb' }, { a: 'intention', b: 'execution' }],
  knapsack: [{ weights: [], values: [], capacity: 10 }, { weights: [2], values: [3], capacity: 4 }, { weights: [3, 3], values: [5, 6], capacity: 3 }, { weights: [1, 2, 3], values: [0, 0, 0], capacity: 6 }],
  'max-subarray': [[-1], [-5, -2, -9], [0, 0], [5, -1, 5], [-2, 3, -1, 4, -10]],
  'stack-ops': [[], [['pop'], ['peek']], [['push', 0], ['peek'], ['pop'], ['peek']], [['push', 1], ['push', 2], ['pop'], ['push', 3], ['pop'], ['pop']]],
  'queue-ops': [[], [['dequeue'], ['enqueue', 0], ['front'], ['dequeue'], ['dequeue']], [['enqueue', 1], ['enqueue', 2], ['dequeue'], ['enqueue', 3], ['dequeue'], ['front']]],
  'balanced-brackets': ['(', ')(', '([]{})', '([)', '()', '['.repeat(1_000) + ']'.repeat(1_000)],
  'frequency-map': [[], ['a', 'A', 'a', ''], ['__proto__', 'constructor', '__proto__'], ['', '']],
  'linked-list-reverse': [{ head: 0, nodes: [{ value: 1, next: null }] }, { head: 2, nodes: [{ value: 2, next: 1 }, { value: 3, next: null }, { value: 1, next: 0 }] }],
  'remove-duplicates': [[], [0, 0, -1, 0, -1], [3, 2, 1], [1, 1, 1]],
  'bst-search': [{ root: null, nodes: [], target: 0 }, { root: 0, nodes: [{ value: 3, left: null, right: null }], target: 2 }, { root: 0, nodes: [{ value: 5, left: 1, right: null }, { value: 2, left: null, right: null }], target: 2 }],
  'tree-height': [{ root: 0, nodes: [{ value: 0, left: null, right: null }] }, { root: 1, nodes: [{ value: 4, left: null, right: null }, { value: 5, left: 0, right: 2 }, { value: 6, left: null, right: null }] }],
  'level-order': [{ root: null, nodes: [] }, { root: 1, nodes: [{ value: 4, left: null, right: null }, { value: 5, left: null, right: 0 }] }],
  'lru-cache': [{ capacity: 0, operations: [['put', 'a', 3], ['get', 'a']] }, { capacity: 1, operations: [['put', 'a', 0], ['get', 'a'], ['put', 'b', 3], ['get', 'a']] }, { capacity: 2, operations: [['put', 'a', 1], ['put', 'b', 2], ['put', 'a', 7], ['put', 'c', 3], ['get', 'a'], ['get', 'b']] }],
  'union-find': [{ n: 2, operations: [['connected', 0, 0], ['union', 0, 0], ['connected', 0, 1]] }, { n: 3, operations: [['union', 0, 1], ['union', 1, 2], ['union', 2, 0], ['connected', 0, 2]] }],
  'trie-prefix': [{ words: [], prefixes: ['', 'a'] }, { words: ['', '', 'a', 'ab'], prefixes: ['', 'a', 'ab', 'abc'] }, { words: ['a', 'a'], prefixes: ['a'] }],
  'range-sum': [{ values: [0], operations: [['sum', 0, 0], ['set', 0, -3], ['sum', 0, 0], ['set', 0, -3], ['sum', 0, 0]] }, { values: [1, 2, 3], operations: [['sum', 0, 2], ['set', 0, 5], ['sum', 0, 1], ['sum', 2, 2]] }],
  'median-stream': [[], [0], [0, 0, 0], [-5, -1, -2, -8], [1, 2, 3, 4, 5, 6], [10, 9, 8, 7, 6]],
  'heap-top-k': [{ values: [], k: 0 }, { values: [-3, -1, -2], k: 2 }, { values: [2, 2, 2], k: 2 }, { values: [1, 3, 2], k: 3 }],
};
