/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=BffEnv` (hash: 417668e570c7c3befaae7688e445591c)
interface __BaseEnv_BffEnv {
	APP_ORIGIN: "https://rodsleet.com";
	APP_ORIGIN_ALIASES: "https://rods-leet.pages.dev";
	SUPABASE_URL: "https://bsjcuygtpiqyomnulpsw.supabase.co";
	GOOGLE_LOGIN_ENABLED: "true";
	SUPABASE_ANON_KEY: string;
	BFF_SHARED_SECRET: string;
	BFF_ENCRYPTION_KEY: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_BffEnv {}
}
interface BffEnv extends __BaseEnv_BffEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ORIGIN" | "APP_ORIGIN_ALIASES" | "SUPABASE_URL" | "GOOGLE_LOGIN_ENABLED" | "SUPABASE_ANON_KEY" | "BFF_SHARED_SECRET" | "BFF_ENCRYPTION_KEY">> {}
}
