import type { Attempt, Difficulty, GameMode, Verdict } from '../lib/contracts';
import { HARD_MINUTES } from './rules';

const timestamp = (value: string): number => {
  const ms = Date.parse(value);
  if (!Number.isFinite(ms)) throw new Error('Data inválida');
  return ms;
};
export interface AttemptState extends Attempt {
  pendingSubmissionIds: string[];
  finalizedSubmissionIds: string[];
}
export function createAttempt(input: {
  id: string; challengeId: string; challengeVersionId: string;
  mode: GameMode; difficulty: Difficulty; serverNow: string;
  hintsUsed?: number; practiceOnly?: boolean; solutionAvailable?: boolean;
}): AttemptState {
  const started = timestamp(input.serverNow);
  return {
    id: input.id, challengeId: input.challengeId, challengeVersionId: input.challengeVersionId,
    mode: input.mode, startedAt: new Date(started).toISOString(),
    deadlineAt: input.mode === 'hard' ? new Date(started + HARD_MINUTES[input.difficulty] * 60_000).toISOString() : null,
    status: 'active', rejectedCount: 0, pendingCount: 0,
    hintsUsed: input.hintsUsed ?? 0, practiceOnly: input.practiceOnly ?? false,
    solutionAvailable: input.solutionAvailable ?? false,
    pendingSubmissionIds: [], finalizedSubmissionIds: [],
  };
}
/** serverReceivedAt is generated by the API; never accept a client timestamp. */
export function queueSubmission(attempt: AttemptState, submissionId: string, serverReceivedAt: string): AttemptState {
  if (attempt.pendingSubmissionIds.includes(submissionId) || attempt.finalizedSubmissionIds.includes(submissionId)) return attempt;
  if (attempt.status !== 'active') throw new Error('Esta sessão já foi encerrada');
  const receivedAt = timestamp(serverReceivedAt);
  if (receivedAt < timestamp(attempt.startedAt)) throw new Error('A submissão antecede a sessão');
  if (attempt.deadlineAt && receivedAt > timestamp(attempt.deadlineAt)) throw new Error('O tempo desta sessão terminou');
  if (attempt.pendingCount > 0) throw new Error('Aguarde a avaliação em andamento');
  if (attempt.mode === 'hard' && attempt.rejectedCount + attempt.pendingCount >= 3) throw new Error('Você utilizou as três submissões');
  return { ...attempt, pendingCount: attempt.pendingCount + 1, pendingSubmissionIds: [...attempt.pendingSubmissionIds, submissionId] };
}
export function finishSubmission(attempt: AttemptState, submissionId: string, verdict: Verdict): AttemptState {
  if (attempt.finalizedSubmissionIds.includes(submissionId)) return attempt;
  if (!attempt.pendingSubmissionIds.includes(submissionId)) throw new Error('Submissão não pertence à sessão');
  const next: AttemptState = {
    ...attempt,
    pendingCount: attempt.pendingCount - 1,
    pendingSubmissionIds: attempt.pendingSubmissionIds.filter(id => id !== submissionId),
    finalizedSubmissionIds: [...attempt.finalizedSubmissionIds, submissionId],
  };
  if (verdict === 'infrastructure_error') return next;
  if (verdict === 'accepted') {
    // A submission received before the deadline remains eligible after expiry.
    next.status = 'accepted';
    next.solutionAvailable = true;
  } else {
    next.rejectedCount += 1;
    if (next.mode === 'hard' && next.rejectedCount >= 3) next.status = 'failed';
    if (next.rejectedCount >= 3) next.solutionAvailable = true;
  }
  return next;
}
export function expireAttempt(attempt: AttemptState, serverNow: string): AttemptState {
  if (attempt.status !== 'active' || !attempt.deadlineAt || timestamp(serverNow) <= timestamp(attempt.deadlineAt)) return attempt;
  return { ...attempt, status: 'expired' };
}
export function abandonAttempt(attempt: AttemptState): AttemptState {
  return attempt.status === 'active' ? { ...attempt, status: 'abandoned' } : attempt;
}
export function canStartBossSession(previousStartedAt: readonly string[], serverNow: string): boolean {
  const now = timestamp(serverNow);
  return previousStartedAt.filter(at => timestamp(at) > now - 24 * 60 * 60_000 && timestamp(at) <= now).length < 3;
}
