import type { ShopItem, ShopCollection } from "../lib/contracts";

/** Public presentation only; purchase authorization and rewards are server-owned. */
export const SHOP_ITEMS: readonly ShopItem[] = [
  {
    id: "hint-extra",
    name: "Dica extra",
    description: "1 dica adicional. O uso mantém a redução de XP do desafio.",
    kind: "hint",
    price: 30,
    minLevel: 0,
    value: "1",
    rarity: "common",
    acquisition: "purchase",
    hintCount: 1,
  },
  {
    id: "avatar-robot",
    name: "Robô explorador",
    description: "Um personagem para acompanhar suas descobertas e desafios.",
    kind: "avatar",
    price: 100,
    minLevel: 0,
    value: "🤖",
    rarity: "common",
    acquisition: "purchase",
  },
  {
    id: "avatar-fox",
    name: "Raposa curiosa",
    description: "Um personagem para acompanhar suas descobertas e desafios.",
    kind: "avatar",
    price: 150,
    minLevel: 2,
    value: "🦊",
    rarity: "common",
    acquisition: "purchase",
  },
  {
    id: "avatar-scholar",
    name: "Coruja sábia",
    description: "Presente ao alcançar o nível 5.",
    kind: "avatar",
    price: 0,
    minLevel: 5,
    value: "🦉",
    rarity: "epic",
    acquisition: "milestone",
  },
  {
    id: "avatar-flame",
    name: "Chama constante",
    description: "Presente por uma sequência de 30 dias.",
    kind: "avatar",
    price: 0,
    minLevel: 0,
    value: "🔥",
    rarity: "epic",
    acquisition: "milestone",
  },
  {
    id: "name-cyan",
    name: "Nome ciano",
    description: "Uma nova cor para seu nome no perfil e no ranking.",
    kind: "name_color",
    price: 100,
    minLevel: 0,
    value: "#22d3ee",
    rarity: "common",
    acquisition: "purchase",
  },
  {
    id: "name-violet",
    name: "Nome violeta",
    description: "Uma nova cor para seu nome no perfil e no ranking.",
    kind: "name_color",
    price: 150,
    minLevel: 3,
    value: "#c4b5fd",
    rarity: "rare",
    acquisition: "purchase",
  },
  {
    id: "theme-ocean",
    name: "Oceano",
    description: "Uma paleta completa para personalizar seu espaço de estudo.",
    kind: "theme",
    price: 200,
    minLevel: 2,
    value: "ocean",
    rarity: "rare",
    acquisition: "purchase",
  },
  {
    id: "theme-sunset",
    name: "Pôr do sol",
    description: "Uma paleta completa para personalizar seu espaço de estudo.",
    kind: "theme",
    price: 250,
    minLevel: 5,
    value: "sunset",
    rarity: "rare",
    acquisition: "purchase",
  },
  {
    id: "hint-pack3",
    name: "Pacote de 3 dicas",
    description:
      "3 dicas adicionais com desconto. O uso mantém a redução de XP do desafio.",
    kind: "hint",
    price: 75,
    minLevel: 0,
    value: "3",
    rarity: "common",
    acquisition: "purchase",
    hintCount: 3,
  },
  {
    id: "hint-pack10",
    name: "Pacote de 10 dicas",
    description:
      "10 dicas adicionais com desconto. O uso mantém a redução de XP do desafio.",
    kind: "hint",
    price: 220,
    minLevel: 0,
    value: "10",
    rarity: "rare",
    acquisition: "purchase",
    hintCount: 10,
  },
  {
    id: "avatar-robot-neon",
    name: "Robô Neon",
    description: "Um personagem para acompanhar suas descobertas e desafios.",
    kind: "avatar",
    price: 300,
    minLevel: 2,
    value: "robot-neon",
    rarity: "rare",
    acquisition: "purchase",
    collectionId: "neon",
  },
  {
    id: "name-neon-lime",
    name: "Nome lima Neon",
    description: "Uma nova cor para seu nome no perfil e no ranking.",
    kind: "name_color",
    price: 200,
    minLevel: 0,
    value: "#bef264",
    rarity: "common",
    acquisition: "purchase",
    collectionId: "neon",
  },
  {
    id: "theme-neon",
    name: "Cidade Neon",
    description: "Uma paleta completa para personalizar seu espaço de estudo.",
    kind: "theme",
    price: 450,
    minLevel: 3,
    value: "neon",
    rarity: "epic",
    acquisition: "purchase",
    collectionId: "neon",
  },
  {
    id: "frame-neon",
    name: "Circuito Neon",
    description:
      "Uma moldura para destacar seu personagem no perfil e no ranking.",
    kind: "frame",
    price: 250,
    minLevel: 2,
    value: "neon",
    rarity: "rare",
    acquisition: "purchase",
    collectionId: "neon",
  },
  {
    id: "title-neon",
    name: "Pulso Neon",
    description:
      "Presente exclusivo ao completar todos os itens desta coleção.",
    kind: "title",
    price: 0,
    minLevel: 0,
    value: "Pulso Neon",
    rarity: "epic",
    acquisition: "collection",
    collectionId: "neon",
  },
  {
    id: "avatar-astronaut",
    name: "Astronauta",
    description: "Um personagem para acompanhar suas descobertas e desafios.",
    kind: "avatar",
    price: 300,
    minLevel: 2,
    value: "astronaut",
    rarity: "rare",
    acquisition: "purchase",
    collectionId: "astral",
  },
  {
    id: "name-rose",
    name: "Nome rosa estelar",
    description: "Uma nova cor para seu nome no perfil e no ranking.",
    kind: "name_color",
    price: 200,
    minLevel: 0,
    value: "#f9a8d4",
    rarity: "common",
    acquisition: "purchase",
    collectionId: "astral",
  },
  {
    id: "theme-cosmos",
    name: "Cosmos",
    description: "Uma paleta completa para personalizar seu espaço de estudo.",
    kind: "theme",
    price: 450,
    minLevel: 3,
    value: "cosmos",
    rarity: "epic",
    acquisition: "purchase",
    collectionId: "astral",
  },
  {
    id: "frame-orbit",
    name: "Órbita estelar",
    description:
      "Uma moldura para destacar seu personagem no perfil e no ranking.",
    kind: "frame",
    price: 250,
    minLevel: 2,
    value: "orbit",
    rarity: "rare",
    acquisition: "purchase",
    collectionId: "astral",
  },
  {
    id: "title-astral",
    name: "Explorador Astral",
    description:
      "Presente exclusivo ao completar todos os itens desta coleção.",
    kind: "title",
    price: 0,
    minLevel: 0,
    value: "Explorador Astral",
    rarity: "epic",
    acquisition: "collection",
    collectionId: "astral",
  },
  {
    id: "avatar-dragon",
    name: "Dragão do Bosque",
    description: "Um personagem para acompanhar suas descobertas e desafios.",
    kind: "avatar",
    price: 350,
    minLevel: 2,
    value: "dragon",
    rarity: "rare",
    acquisition: "purchase",
    collectionId: "forest",
  },
  {
    id: "name-emerald",
    name: "Nome esmeralda",
    description: "Uma nova cor para seu nome no perfil e no ranking.",
    kind: "name_color",
    price: 200,
    minLevel: 0,
    value: "#6ee7b7",
    rarity: "common",
    acquisition: "purchase",
    collectionId: "forest",
  },
  {
    id: "theme-forest",
    name: "Bosque",
    description: "Uma paleta completa para personalizar seu espaço de estudo.",
    kind: "theme",
    price: 400,
    minLevel: 3,
    value: "forest",
    rarity: "epic",
    acquisition: "purchase",
    collectionId: "forest",
  },
  {
    id: "frame-vine",
    name: "Ramos do Bosque",
    description:
      "Uma moldura para destacar seu personagem no perfil e no ranking.",
    kind: "frame",
    price: 250,
    minLevel: 2,
    value: "vine",
    rarity: "rare",
    acquisition: "purchase",
    collectionId: "forest",
  },
  {
    id: "title-forest",
    name: "Guardião do Bosque",
    description:
      "Presente exclusivo ao completar todos os itens desta coleção.",
    kind: "title",
    price: 0,
    minLevel: 0,
    value: "Guardião do Bosque",
    rarity: "epic",
    acquisition: "collection",
    collectionId: "forest",
  },
  {
    id: "avatar-ninja",
    name: "Ninja do código",
    description: "Um personagem para acompanhar suas descobertas e desafios.",
    kind: "avatar",
    price: 350,
    minLevel: 3,
    value: "ninja",
    rarity: "rare",
    acquisition: "purchase",
  },
  {
    id: "frame-pixel",
    name: "Pixels clássicos",
    description:
      "Uma moldura para destacar seu personagem no perfil e no ranking.",
    kind: "frame",
    price: 150,
    minLevel: 0,
    value: "pixel",
    rarity: "common",
    acquisition: "purchase",
  },
  {
    id: "title-curious",
    name: "Pessoa curiosa",
    description: "Um título para acompanhar seu nome e suas conquistas.",
    kind: "title",
    price: 100,
    minLevel: 0,
    value: "Pessoa curiosa",
    rarity: "common",
    acquisition: "purchase",
  },
  {
    id: "title-persistent",
    name: "Sempre aprendendo",
    description: "Um título para acompanhar seu nome e suas conquistas.",
    kind: "title",
    price: 150,
    minLevel: 1,
    value: "Sempre aprendendo",
    rarity: "common",
    acquisition: "purchase",
  },
  {
    id: "title-debugger",
    name: "Caça-bugs",
    description: "Um título para acompanhar seu nome e suas conquistas.",
    kind: "title",
    price: 200,
    minLevel: 2,
    value: "Caça-bugs",
    rarity: "rare",
    acquisition: "purchase",
  },
  {
    id: "title-algorithm",
    name: "Arquiteto de algoritmos",
    description: "Um título para acompanhar seu nome e suas conquistas.",
    kind: "title",
    price: 350,
    minLevel: 5,
    value: "Arquiteto de algoritmos",
    rarity: "epic",
    acquisition: "purchase",
  },
  {
    id: "frame-champion",
    name: "Campeão semanal",
    description:
      "Premiação permanente por posição no ranking semanal; não está à venda.",
    kind: "frame",
    price: 0,
    minLevel: 0,
    value: "champion",
    rarity: "legendary",
    acquisition: "ranking",
  },
  {
    id: "frame-runnerup",
    name: "Vice-campeão semanal",
    description:
      "Premiação permanente por posição no ranking semanal; não está à venda.",
    kind: "frame",
    price: 0,
    minLevel: 0,
    value: "runnerup",
    rarity: "legendary",
    acquisition: "ranking",
  },
  {
    id: "frame-bronze",
    name: "Bronze semanal",
    description:
      "Premiação permanente por posição no ranking semanal; não está à venda.",
    kind: "frame",
    price: 0,
    minLevel: 0,
    value: "bronze",
    rarity: "legendary",
    acquisition: "ranking",
  },
  {
    id: "frame-finalist4",
    name: "Finalista semanal IV",
    description:
      "Premiação permanente por posição no ranking semanal; não está à venda.",
    kind: "frame",
    price: 0,
    minLevel: 0,
    value: "finalist4",
    rarity: "legendary",
    acquisition: "ranking",
  },
  {
    id: "frame-finalist5",
    name: "Finalista semanal V",
    description:
      "Premiação permanente por posição no ranking semanal; não está à venda.",
    kind: "frame",
    price: 0,
    minLevel: 0,
    value: "finalist5",
    rarity: "legendary",
    acquisition: "ranking",
  },
];

export const SHOP_COLLECTIONS: readonly ShopCollection[] = [
  {
    id: "neon",
    name: "Neon",
    description: "Complete o conjunto Neon para ganhar um título exclusivo.",
    itemIds: [
      "avatar-robot-neon",
      "name-neon-lime",
      "theme-neon",
      "frame-neon",
    ],
    rewardItemId: "title-neon",
  },
  {
    id: "astral",
    name: "Astral",
    description: "Complete o conjunto Astral para ganhar um título exclusivo.",
    itemIds: ["avatar-astronaut", "name-rose", "theme-cosmos", "frame-orbit"],
    rewardItemId: "title-astral",
  },
  {
    id: "forest",
    name: "Bosque",
    description: "Complete o conjunto Bosque para ganhar um título exclusivo.",
    itemIds: ["avatar-dragon", "name-emerald", "theme-forest", "frame-vine"],
    rewardItemId: "title-forest",
  },
];

export const WEEKLY_PRIZES = [
  { position: 1, coins: 500, itemId: "frame-champion" },
  { position: 2, coins: 350, itemId: "frame-runnerup" },
  { position: 3, coins: 250, itemId: "frame-bronze" },
  { position: 4, coins: 150, itemId: "frame-finalist4" },
  { position: 5, coins: 100, itemId: "frame-finalist5" },
] as const;
